export const countries = [
  {
    id: "AF",
    flag: "AFG",
    country: "Afghanistan",
    areaCode: "+93",
    currencyCode: "AFN",
  },
  {
    id: "AX",
    flag: "ALA",
    country: "\u00c5land Islands",
    areaCode: "+358",
    currencyCode: "EUR",
  },
  {
    id: "AL",
    flag: "ALB",
    country: "Albania",
    areaCode: "+355",
    currencyCode: "ALL",
  },
  {
    id: "DZ",
    flag: "DZA",
    country: "Algeria",
    areaCode: "+213",
    currencyCode: "DZD",
  },
  {
    id: "AS",
    flag: "ASM",
    country: "American Samoa",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "AD",
    flag: "AND",
    country: "Andorra",
    areaCode: "+376",
    currencyCode: "EUR",
  },
  {
    id: "AO",
    flag: "AGO",
    country: "Angola",
    areaCode: "+244",
    currencyCode: "AOA",
  },
  {
    id: "AI",
    flag: "AIA",
    country: "Anguilla",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "AQ",
    flag: "ATA",
    country: "Antarctica",
    areaCode: "+672",
    currencyCode: "AUD",
  },
  {
    id: "AG",
    flag: "ATG",
    country: "Antigua and Barbuda",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "AR",
    flag: "ARG",
    country: "Argentina",
    areaCode: "+54",
    currencyCode: "ARS",
  },
  {
    id: "AM",
    flag: "ARM",
    country: "Armenia",
    areaCode: "+374",
    currencyCode: "AMD",
  },
  {
    id: "AW",
    flag: "ABW",
    country: "Aruba",
    areaCode: "+297",
    currencyCode: "AWG",
  },
  {
    id: "AU",
    flag: "AUS",
    country: "Australia",
    areaCode: "+61",
    currencyCode: "AUD",
  },
  {
    id: "AT",
    flag: "AUT",
    country: "Austria",
    areaCode: "+43",
    currencyCode: "EUR",
  },
  {
    id: "AZ",
    flag: "AZE",
    country: "Azerbaijan",
    areaCode: "+994",
    currencyCode: "AZN",
  },
  {
    id: "BS",
    flag: "BHS",
    country: "Bahamas",
    areaCode: "+1",
    currencyCode: "BSD",
  },
  {
    id: "BH",
    flag: "BHR",
    country: "Bahrain",
    areaCode: "+973",
    currencyCode: "BHD",
  },
  {
    id: "BD",
    flag: "BGD",
    country: "Bangladesh",
    areaCode: "+880",
    currencyCode: "BDT",
  },
  {
    id: "BB",
    flag: "BRB",
    country: "Barbados",
    areaCode: "+1",
    currencyCode: "BBD",
  },
  {
    id: "BY",
    flag: "BLR",
    country: "Belarus",
    areaCode: "+375",
    currencyCode: "BYN",
  },
  {
    id: "BE",
    flag: "BEL",
    country: "Belgium",
    areaCode: "+32",
    currencyCode: "EUR",
  },
  {
    id: "BZ",
    flag: "BLZ",
    country: "Belize",
    areaCode: "+501",
    currencyCode: "BZD",
  },
  {
    id: "BJ",
    flag: "BEN",
    country: "Benin",
    areaCode: "+229",
    currencyCode: "XOF",
  },
  {
    id: "BM",
    flag: "BMU",
    country: "Bermuda",
    areaCode: "+1",
    currencyCode: "BMD",
  },
  {
    id: "BT",
    flag: "BTN",
    country: "Bhutan",
    areaCode: "+975",
    currencyCode: "BTN",
  },
  {
    id: "BO",
    flag: "BOL",
    country: "Bolivia",
    areaCode: "+591",
    currencyCode: "BOB",
  },
  {
    id: "BA",
    flag: "BIH",
    country: "Bosnia and Herzegovina",
    areaCode: "+387",
    currencyCode: "BAM",
  },
  {
    id: "BW",
    flag: "BWA",
    country: "Botswana",
    areaCode: "+267",
    currencyCode: "BWP",
  },
  {
    id: "BR",
    flag: "BRA",
    country: "Brazil",
    areaCode: "+55",
    currencyCode: "BRL",
  },
  {
    id: "IO",
    flag: "IOT",
    country: "British Indian Ocean Territory",
    areaCode: "+246",
    currencyCode: "USD",
  },
  {
    id: "VG",
    flag: "VGB",
    country: "British Virgin Islands",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "BN",
    flag: "BRN",
    country: "Brunei",
    areaCode: "+673",
    currencyCode: "BND",
  },
  {
    id: "BG",
    flag: "BGR",
    country: "Bulgaria",
    areaCode: "+359",
    currencyCode: "BGN",
  },
  {
    id: "BF",
    flag: "BFA",
    country: "Burkina Faso",
    areaCode: "+226",
    currencyCode: "XOF",
  },
  {
    id: "BI",
    flag: "BDI",
    country: "Burundi",
    areaCode: "+257",
    currencyCode: "BIF",
  },
  {
    id: "KH",
    flag: "KHM",
    country: "Cambodia",
    areaCode: "+855",
    currencyCode: "KHR",
  },
  {
    id: "CM",
    flag: "CMR",
    country: "Cameroon",
    areaCode: "+237",
    currencyCode: "XAF",
  },
  {
    id: "CA",
    flag: "CAN",
    country: "Canada",
    areaCode: "+1",
    currencyCode: "CAD",
  },
  {
    id: "CV",
    flag: "CPV",
    country: "Cape Verde",
    areaCode: "+238",
    currencyCode: "CVE",
  },
  {
    id: "BQ",
    flag: "BES",
    country: "Caribbean Netherlands",
    areaCode: "+599",
    currencyCode: "USD",
  },
  {
    id: "KY",
    flag: "CYM",
    country: "Cayman Islands",
    areaCode: "+1",
    currencyCode: "KYD",
  },
  {
    id: "CF",
    flag: "CAF",
    country: "Central African Republic",
    areaCode: "+236",
    currencyCode: "XAF",
  },
  {
    id: "TD",
    flag: "TCD",
    country: "Chad",
    areaCode: "+235",
    currencyCode: "XAF",
  },
  {
    id: "CL",
    flag: "CHL",
    country: "Chile",
    areaCode: "+56",
    currencyCode: "CLP",
  },
  {
    id: "CN",
    flag: "CHN",
    country: "China",
    areaCode: "+86",
    currencyCode: "CNY",
  },
  {
    id: "CX",
    flag: "CXR",
    country: "Christmas Island",
    areaCode: "+61",
    currencyCode: "AUD",
  },
  {
    id: "CC",
    flag: "CCK",
    country: "Cocos (Keeling) Islands",
    areaCode: "+61",
    currencyCode: "AUD",
  },
  {
    id: "CO",
    flag: "COL",
    country: "Colombia",
    areaCode: "+57",
    currencyCode: "COP",
  },
  {
    id: "KM",
    flag: "COM",
    country: "Comoros",
    areaCode: "+269",
    currencyCode: "KMF",
  },
  {
    id: "CG",
    flag: "COG",
    country: "Congo (Brazzaville)",
    areaCode: "+242",
    currencyCode: "XAF",
  },
  {
    id: "CD",
    flag: "COD",
    country: "Congo (Kinshasa)",
    areaCode: "+243",
    currencyCode: "CDF",
  },
  {
    id: "CK",
    flag: "COK",
    country: "Cook Islands",
    areaCode: "+682",
    currencyCode: "NZD",
  },
  {
    id: "CR",
    flag: "CRI",
    country: "Costa Rica",
    areaCode: "+506",
    currencyCode: "CRC",
  },
  {
    id: "HR",
    flag: "HRV",
    country: "Croatia",
    areaCode: "+385",
    currencyCode: "HRK",
  },
  {
    id: "CU",
    flag: "CUB",
    country: "Cuba",
    areaCode: "+53",
    currencyCode: "CUP",
  },
  {
    id: "CW",
    flag: "CUW",
    country: "Cura\u00e7ao",
    areaCode: "+599",
    currencyCode: "ANG",
  },
  {
    id: "CY",
    flag: "CYP",
    country: "Cyprus",
    areaCode: "+357",
    currencyCode: "EUR",
  },
  {
    id: "CZ",
    flag: "CZE",
    country: "Czech Republic",
    areaCode: "+420",
    currencyCode: "CZK",
  },
  {
    id: "DK",
    flag: "DNK",
    country: "Denmark",
    areaCode: "+45",
    currencyCode: "DKK",
  },
  {
    id: "DJ",
    flag: "DJI",
    country: "Djibouti",
    areaCode: "+253",
    currencyCode: "DJF",
  },
  {
    id: "DM",
    flag: "DMA",
    country: "Dominica",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "DO",
    flag: "DOM",
    country: "Dominican Republic",
    areaCode: "+1",
    currencyCode: "DOP",
  },
  {
    id: "EC",
    flag: "ECU",
    country: "Ecuador",
    areaCode: "+593",
    currencyCode: "USD",
  },
  {
    id: "EG",
    flag: "EGY",
    country: "Egypt",
    areaCode: "+20",
    currencyCode: "EGP",
  },
  {
    id: "SV",
    flag: "SLV",
    country: "El Salvador",
    areaCode: "+503",
    currencyCode: "USD",
  },
  {
    id: "GQ",
    flag: "GNQ",
    country: "Equatorial Guinea",
    areaCode: "+240",
    currencyCode: "XAF",
  },
  {
    id: "ER",
    flag: "ERI",
    country: "Eritrea",
    areaCode: "+291",
    currencyCode: "ERN",
  },
  {
    id: "EE",
    flag: "EST",
    country: "Estonia",
    areaCode: "+372",
    currencyCode: "EUR",
  },
  {
    id: "ET",
    flag: "ETH",
    country: "Ethiopia",
    areaCode: "+251",
    currencyCode: "ETB",
  },
  {
    id: "FK",
    flag: "FLK",
    country: "Falkland Islands",
    areaCode: "+500",
    currencyCode: "FKP",
  },
  {
    id: "FO",
    flag: "FRO",
    country: "Faroe Islands",
    areaCode: "+298",
    currencyCode: "DKK",
  },
  {
    id: "FJ",
    flag: "FJI",
    country: "Fiji",
    areaCode: "+679",
    currencyCode: "FJD",
  },
  {
    id: "FI",
    flag: "FIN",
    country: "Finland",
    areaCode: "+358",
    currencyCode: "EUR",
  },
  {
    id: "FR",
    flag: "FRA",
    country: "France",
    areaCode: "+33",
    currencyCode: "EUR",
  },
  {
    id: "GF",
    flag: "GUF",
    country: "French Guiana",
    areaCode: "+594",
    currencyCode: "EUR",
  },
  {
    id: "PF",
    flag: "PYF",
    country: "French Polynesia",
    areaCode: "+689",
    currencyCode: "XPF",
  },
  {
    id: "TF",
    flag: "ATF",
    country: "French Southern and Antarctic Lands",
    areaCode: "+262",
    currencyCode: "EUR",
  },
  {
    id: "GA",
    flag: "GAB",
    country: "Gabon",
    areaCode: "+241",
    currencyCode: "XAF",
  },
  {
    id: "GM",
    flag: "GMB",
    country: "Gambia",
    areaCode: "+220",
    currencyCode: "GMD",
  },
  {
    id: "GE",
    flag: "GEO",
    country: "Georgia",
    areaCode: "+995",
    currencyCode: "GEL",
  },
  {
    id: "DE",
    flag: "DEU",
    country: "Germany",
    areaCode: "+49",
    currencyCode: "EUR",
  },
  {
    id: "GH",
    flag: "GHA",
    country: "Ghana",
    areaCode: "+233",
    currencyCode: "GHS",
  },
  {
    id: "GI",
    flag: "GIB",
    country: "Gibraltar",
    areaCode: "+350",
    currencyCode: "GIP",
  },
  {
    id: "GR",
    flag: "GRC",
    country: "Greece",
    areaCode: "+30",
    currencyCode: "EUR",
  },
  {
    id: "GL",
    flag: "GRL",
    country: "Greenland",
    areaCode: "+299",
    currencyCode: "DKK",
  },
  {
    id: "GD",
    flag: "GRD",
    country: "Grenada",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "GP",
    flag: "GLP",
    country: "Guadeloupe",
    areaCode: "+590",
    currencyCode: "EUR",
  },
  {
    id: "GU",
    flag: "GUM",
    country: "Guam",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "GT",
    flag: "GTM",
    country: "Guatemala",
    areaCode: "+502",
    currencyCode: "GTQ",
  },
  {
    id: "GG",
    flag: "GGY",
    country: "Guernsey",
    areaCode: "+44",
    currencyCode: "GBP",
  },
  {
    id: "GN",
    flag: "GIN",
    country: "Guinea",
    areaCode: "+224",
    currencyCode: "GNF",
  },
  {
    id: "GW",
    flag: "GNB",
    country: "Guinea-Bissau",
    areaCode: "+245",
    currencyCode: "XOF",
  },
  {
    id: "GY",
    flag: "GUY",
    country: "Guyana",
    areaCode: "+592",
    currencyCode: "GYD",
  },
  {
    id: "HT",
    flag: "HTI",
    country: "Haiti",
    areaCode: "+509",
    currencyCode: "HTG",
  },
  {
    id: "HM",
    flag: "HMD",
    country: "Heard Island and McDonald Islands",
    areaCode: "+",
    currencyCode: "AUD",
  },
  {
    id: "HN",
    flag: "HND",
    country: "Honduras",
    areaCode: "+504",
    currencyCode: "HNL",
  },
  {
    id: "HK",
    flag: "HKG",
    country: "Hong Kong",
    areaCode: "+852",
    currencyCode: "HKD",
  },
  {
    id: "HU",
    flag: "HUN",
    country: "Hungary",
    areaCode: "+36",
    currencyCode: "HUF",
  },
  {
    id: "IS",
    flag: "ISL",
    country: "Iceland",
    areaCode: "+354",
    currencyCode: "ISK",
  },
  {
    id: "IN",
    flag: "IND",
    country: "India",
    areaCode: "+91",
    currencyCode: "INR",
  },
  {
    id: "ID",
    flag: "IDN",
    country: "Indonesia",
    areaCode: "+62",
    currencyCode: "IDR",
  },
  {
    id: "IR",
    flag: "IRN",
    country: "Iran",
    areaCode: "+98",
    currencyCode: "IRR",
  },
  {
    id: "IQ",
    flag: "IRQ",
    country: "Iraq",
    areaCode: "+964",
    currencyCode: "IQD",
  },
  {
    id: "IE",
    flag: "IRL",
    country: "Ireland",
    areaCode: "+353",
    currencyCode: "EUR",
  },
  {
    id: "IM",
    flag: "IMN",
    country: "Isle of Man",
    areaCode: "+44",
    currencyCode: "GBP",
  },
  {
    id: "IL",
    flag: "ISR",
    country: "Israel",
    areaCode: "+972",
    currencyCode: "ILS",
  },
  {
    id: "IT",
    flag: "ITA",
    country: "Italy",
    areaCode: "+39",
    currencyCode: "EUR",
  },
  {
    id: "CI",
    flag: "CIV",
    country: "Ivory Coast",
    areaCode: "+225",
    currencyCode: "XOF",
  },
  {
    id: "JM",
    flag: "JAM",
    country: "Jamaica",
    areaCode: "+1",
    currencyCode: "JMD",
  },
  {
    id: "JP",
    flag: "JPN",
    country: "Japan",
    areaCode: "+81",
    currencyCode: "JPY",
  },
  {
    id: "JE",
    flag: "JEY",
    country: "Jersey",
    areaCode: "+44",
    currencyCode: "GBP",
  },
  {
    id: "JO",
    flag: "JOR",
    country: "Jordan",
    areaCode: "+962",
    currencyCode: "JOD",
  },
  {
    id: "KZ",
    flag: "KAZ",
    country: "Kazakhstan",
    areaCode: "+7",
    currencyCode: "KZT",
  },
  {
    id: "KE",
    flag: "KEN",
    country: "Kenya",
    areaCode: "+254",
    currencyCode: "KES",
  },
  {
    id: "KI",
    flag: "KIR",
    country: "Kiribati",
    areaCode: "+686",
    currencyCode: "AUD",
  },
  {
    id: "KW",
    flag: "KWT",
    country: "Kuwait",
    areaCode: "+965",
    currencyCode: "KWD",
  },
  {
    id: "KG",
    flag: "KGZ",
    country: "Kyrgyzstan",
    areaCode: "+996",
    currencyCode: "KGS",
  },
  {
    id: "LA",
    flag: "LAO",
    country: "Laos",
    areaCode: "+856",
    currencyCode: "LAK",
  },
  {
    id: "LV",
    flag: "LVA",
    country: "Latvia",
    areaCode: "+371",
    currencyCode: "EUR",
  },
  {
    id: "LB",
    flag: "LBN",
    country: "Lebanon",
    areaCode: "+961",
    currencyCode: "LBP",
  },
  {
    id: "LS",
    flag: "LSO",
    country: "Lesotho",
    areaCode: "+266",
    currencyCode: "LSL",
  },
  {
    id: "LR",
    flag: "LBR",
    country: "Liberia",
    areaCode: "+231",
    currencyCode: "LRD",
  },
  {
    id: "LY",
    flag: "LBY",
    country: "Libya",
    areaCode: "+218",
    currencyCode: "LYD",
  },
  {
    id: "LI",
    flag: "LIE",
    country: "Liechtenstein",
    areaCode: "+423",
    currencyCode: "CHF",
  },
  {
    id: "LT",
    flag: "LTU",
    country: "Lithuania",
    areaCode: "+370",
    currencyCode: "EUR",
  },
  {
    id: "LU",
    flag: "LUX",
    country: "Luxembourg",
    areaCode: "+352",
    currencyCode: "EUR",
  },
  {
    id: "MO",
    flag: "MAC",
    country: "Macau",
    areaCode: "+853",
    currencyCode: "MOP",
  },
  {
    id: "MK",
    flag: "MKD",
    country: "Macedonia",
    areaCode: "+389",
    currencyCode: "MKD",
  },
  {
    id: "MG",
    flag: "MDG",
    country: "Madagascar",
    areaCode: "+261",
    currencyCode: "MGA",
  },
  {
    id: "MW",
    flag: "MWI",
    country: "Malawi",
    areaCode: "+265",
    currencyCode: "MWK",
  },
  {
    id: "MY",
    flag: "MYS",
    country: "Malaysia",
    areaCode: "+60",
    currencyCode: "MYR",
  },
  {
    id: "MV",
    flag: "MDV",
    country: "Maldives",
    areaCode: "+960",
    currencyCode: "MVR",
  },
  {
    id: "ML",
    flag: "MLI",
    country: "Mali",
    areaCode: "+223",
    currencyCode: "XOF",
  },
  {
    id: "MT",
    flag: "MLT",
    country: "Malta",
    areaCode: "+356",
    currencyCode: "EUR",
  },
  {
    id: "MH",
    flag: "MHL",
    country: "Marshall Islands",
    areaCode: "+692",
    currencyCode: "USD",
  },
  {
    id: "MQ",
    flag: "MTQ",
    country: "Martinique",
    areaCode: "+596",
    currencyCode: "EUR",
  },
  {
    id: "MR",
    flag: "MRT",
    country: "Mauritania",
    areaCode: "+222",
    currencyCode: "MRU",
  },
  {
    id: "MU",
    flag: "MUS",
    country: "Mauritius",
    areaCode: "+230",
    currencyCode: "MUR",
  },
  {
    id: "YT",
    flag: "MYT",
    country: "Mayotte",
    areaCode: "+262",
    currencyCode: "EUR",
  },
  {
    id: "MX",
    flag: "MEX",
    country: "Mexico",
    areaCode: "+52",
    currencyCode: "MXN",
  },
  {
    id: "FM",
    flag: "FSM",
    country: "Micronesia",
    areaCode: "+691",
    currencyCode: "USD",
  },
  {
    id: "MD",
    flag: "MDA",
    country: "Moldova",
    areaCode: "+373",
    currencyCode: "MDL",
  },
  {
    id: "MC",
    flag: "MCO",
    country: "Monaco",
    areaCode: "+377",
    currencyCode: "EUR",
  },
  {
    id: "MN",
    flag: "MNG",
    country: "Mongolia",
    areaCode: "+976",
    currencyCode: "MNT",
  },
  {
    id: "ME",
    flag: "MNE",
    country: "Montenegro",
    areaCode: "+382",
    currencyCode: "EUR",
  },
  {
    id: "MS",
    flag: "MSR",
    country: "Montserrat",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "MA",
    flag: "MAR",
    country: "Morocco",
    areaCode: "+212",
    currencyCode: "MAD",
  },
  {
    id: "MZ",
    flag: "MOZ",
    country: "Mozambique",
    areaCode: "+258",
    currencyCode: "MZN",
  },
  {
    id: "MM",
    flag: "MMR",
    country: "Myanmar (Burma)",
    areaCode: "+95",
    currencyCode: "MMK",
  },
  {
    id: "NA",
    flag: "NAM",
    country: "Namibia",
    areaCode: "+264",
    currencyCode: "NAD",
  },
  {
    id: "NR",
    flag: "NRU",
    country: "Nauru",
    areaCode: "+674",
    currencyCode: "AUD",
  },
  {
    id: "NP",
    flag: "NPL",
    country: "Nepal",
    areaCode: "+977",
    currencyCode: "NPR",
  },
  {
    id: "NL",
    flag: "NLD",
    country: "Netherlands",
    areaCode: "+31",
    currencyCode: "EUR",
  },
  {
    id: "NC",
    flag: "NCL",
    country: "New Caledonia",
    areaCode: "+687",
    currencyCode: "XPF",
  },
  {
    id: "NZ",
    flag: "NZL",
    country: "New Zealand",
    areaCode: "+64",
    currencyCode: "NZD",
  },
  {
    id: "NI",
    flag: "NIC",
    country: "Nicaragua",
    areaCode: "+505",
    currencyCode: "NIO",
  },
  {
    id: "NE",
    flag: "NER",
    country: "Niger",
    areaCode: "+227",
    currencyCode: "XOF",
  },
  {
    id: "NG",
    flag: "NGA",
    country: "Nigeria",
    areaCode: "+234",
    currencyCode: "NGN",
  },
  {
    id: "NU",
    flag: "NIU",
    country: "Niue",
    areaCode: "+683",
    currencyCode: "NZD",
  },
  {
    id: "NF",
    flag: "NFK",
    country: "Norfolk Island",
    areaCode: "+672",
    currencyCode: "AUD",
  },
  {
    id: "MP",
    flag: "MNP",
    country: "Northern Mariana Islands",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "NO",
    flag: "NOR",
    country: "Norway",
    areaCode: "+47",
    currencyCode: "NOK",
  },
  {
    id: "OM",
    flag: "OMN",
    country: "Oman",
    areaCode: "+968",
    currencyCode: "OMR",
  },
  {
    id: "PK",
    flag: "PAK",
    country: "Pakistan",
    areaCode: "+92",
    currencyCode: "PKR",
  },
  {
    id: "PW",
    flag: "PLW",
    country: "Palau",
    areaCode: "+680",
    currencyCode: "USD",
  },
  {
    id: "PS",
    flag: "PSE",
    country: "Palestinian Territories",
    areaCode: "+970",
    currencyCode: "ILS",
  },
  {
    id: "PA",
    flag: "PAN",
    country: "Panama",
    areaCode: "+507",
    currencyCode: "PAB",
  },
  {
    id: "PG",
    flag: "PNG",
    country: "Papua New Guinea",
    areaCode: "+675",
    currencyCode: "PGK",
  },
  {
    id: "PY",
    flag: "PRY",
    country: "Paraguay",
    areaCode: "+595",
    currencyCode: "PYG",
  },
  {
    id: "PE",
    flag: "PER",
    country: "Peru",
    areaCode: "+51",
    currencyCode: "PEN",
  },
  {
    id: "PH",
    flag: "PHL",
    country: "Philippines",
    areaCode: "+63",
    currencyCode: "PHP",
  },
  {
    id: "PN",
    flag: "PCN",
    country: "Pitcairn Islands",
    areaCode: "+64",
    currencyCode: "NZD",
  },
  {
    id: "PL",
    flag: "POL",
    country: "Poland",
    areaCode: "+48",
    currencyCode: "PLN",
  },
  {
    id: "PT",
    flag: "PRT",
    country: "Portugal",
    areaCode: "+351",
    currencyCode: "EUR",
  },
  {
    id: "PR",
    flag: "PRI",
    country: "Puerto Rico",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "QA",
    flag: "QAT",
    country: "Qatar",
    areaCode: "+974",
    currencyCode: "QAR",
  },
  {
    id: "RE",
    flag: "REU",
    country: "R&eacute;union",
    areaCode: "+262",
    currencyCode: "EUR",
  },
  {
    id: "RO",
    flag: "ROU",
    country: "Romania",
    areaCode: "+40",
    currencyCode: "RON",
  },
  {
    id: "RU",
    flag: "RUS",
    country: "Russia",
    areaCode: "+7",
    currencyCode: "RUB",
  },
  {
    id: "RW",
    flag: "RWA",
    country: "Rwanda",
    areaCode: "+250",
    currencyCode: "RWF",
  },
  {
    id: "BL",
    flag: "BLM",
    country: "Saint Barth&eacute;lemy",
    areaCode: "+590",
    currencyCode: "EUR",
  },
  {
    id: "SH",
    flag: "SHN",
    country: "Saint Helena",
    areaCode: "+290",
    currencyCode: "SHP",
  },
  {
    id: "KN",
    flag: "KNA",
    country: "Saint Kitts and Nevis",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "LC",
    flag: "LCA",
    country: "Saint Lucia",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "MF",
    flag: "MAF",
    country: "Saint Martin",
    areaCode: "+590",
    currencyCode: "EUR",
  },
  {
    id: "PM",
    flag: "SPM",
    country: "Saint Pierre and Miquelon",
    areaCode: "+508",
    currencyCode: "EUR",
  },
  {
    id: "VC",
    flag: "VCT",
    country: "Saint Vincent and the Grenadines",
    areaCode: "+1",
    currencyCode: "XCD",
  },
  {
    id: "WS",
    flag: "WSM",
    country: "Samoa",
    areaCode: "+685",
    currencyCode: "WST",
  },
  {
    id: "SM",
    flag: "SMR",
    country: "San Marino",
    areaCode: "+378",
    currencyCode: "EUR",
  },
  {
    id: "ST",
    flag: "STP",
    country: "S&atilde;o Tom&eacute; and Pr&iacute;ncipe",
    areaCode: "+239",
    currencyCode: "STN",
  },
  {
    id: "SA",
    flag: "SAU",
    country: "Saudi Arabia",
    areaCode: "+966",
    currencyCode: "SAR",
  },
  {
    id: "SN",
    flag: "SEN",
    country: "Senegal",
    areaCode: "+221",
    currencyCode: "XOF",
  },
  {
    id: "RS",
    flag: "SRB",
    country: "Serbia",
    areaCode: "+381",
    currencyCode: "RSD",
  },
  {
    id: "SC",
    flag: "SYC",
    country: "Seychelles",
    areaCode: "+248",
    currencyCode: "SCR",
  },
  {
    id: "SL",
    flag: "SLE",
    country: "Sierra Leone",
    areaCode: "+232",
    currencyCode: "SLL",
  },
  {
    id: "SG",
    flag: "SGP",
    country: "Singapore",
    areaCode: "+65",
    currencyCode: "SGD",
  },
  {
    id: "SX",
    flag: "SXM",
    country: "Sint Maarten",
    areaCode: "+1",
    currencyCode: "ANG",
  },
  {
    id: "SK",
    flag: "SVK",
    country: "Slovakia",
    areaCode: "+421",
    currencyCode: "EUR",
  },
  {
    id: "SI",
    flag: "SVN",
    country: "Slovenia",
    areaCode: "+386",
    currencyCode: "EUR",
  },
  {
    id: "SB",
    flag: "SLB",
    country: "Solomon Islands",
    areaCode: "+677",
    currencyCode: "SBD",
  },
  {
    id: "SO",
    flag: "SOM",
    country: "Somalia",
    areaCode: "+252",
    currencyCode: "SOS",
  },
  {
    id: "ZA",
    flag: "ZAF",
    country: "South Africa",
    areaCode: "+27",
    currencyCode: "ZAR",
  },
  {
    id: "GS",
    flag: "SGS",
    country: "South Georgia and the South Sandwich Islands",
    areaCode: "+500",
    currencyCode: "GBP",
  },
  {
    id: "KR",
    flag: "KOR",
    country: "South Korea",
    areaCode: "+82",
    currencyCode: "KRW",
  },
  {
    id: "SS",
    flag: "SSD",
    country: "South Sudan",
    areaCode: "+211",
    currencyCode: "SSP",
  },
  {
    id: "ES",
    flag: "ESP",
    country: "Spain",
    areaCode: "+34",
    currencyCode: "EUR",
  },
  {
    id: "LK",
    flag: "LKA",
    country: "Sri Lanka",
    areaCode: "+94",
    currencyCode: "LKR",
  },
  {
    id: "SD",
    flag: "SDN",
    country: "Sudan",
    areaCode: "+249",
    currencyCode: "SDG",
  },
  {
    id: "SR",
    flag: "SUR",
    country: "Suriname",
    areaCode: "+597",
    currencyCode: "SRD",
  },
  {
    id: "SJ",
    flag: "SJM",
    country: "Svalbard and Jan Mayen",
    areaCode: "+47",
    currencyCode: "NOK",
  },
  {
    id: "SZ",
    flag: "SWZ",
    country: "Eswatini",
    areaCode: "+268",
    currencyCode: "SZL",
  },
  {
    id: "SE",
    flag: "SWE",
    country: "Sweden",
    areaCode: "+46",
    currencyCode: "SEK",
  },
  {
    id: "CH",
    flag: "CHE",
    country: "Switzerland",
    areaCode: "+41",
    currencyCode: "CHF",
  },
  {
    id: "SY",
    flag: "SYR",
    country: "Syria",
    areaCode: "+963",
    currencyCode: "SYP",
  },
  {
    id: "TW",
    flag: "TWN",
    country: "Taiwan",
    areaCode: "+886",
    currencyCode: "TWD",
  },
  {
    id: "TJ",
    flag: "TJK",
    country: "Tajikistan",
    areaCode: "+992",
    currencyCode: "TJS",
  },
  {
    id: "TZ",
    flag: "TZA",
    country: "Tanzania",
    areaCode: "+255",
    currencyCode: "TZS",
  },
  {
    id: "TH",
    flag: "THA",
    country: "Thailand",
    areaCode: "+66",
    currencyCode: "THB",
  },
  {
    id: "TL",
    flag: "TLS",
    country: "Timor-Leste",
    areaCode: "+670",
    currencyCode: "USD",
  },
  {
    id: "TG",
    flag: "TGO",
    country: "Togo",
    areaCode: "+228",
    currencyCode: "XOF",
  },
  {
    id: "TK",
    flag: "TKL",
    country: "Tokelau",
    areaCode: "+690",
    currencyCode: "NZD",
  },
  {
    id: "TO",
    flag: "TON",
    country: "Tonga",
    areaCode: "+676",
    currencyCode: "TOP",
  },
  {
    id: "TT",
    flag: "TTO",
    country: "Trinidad and Tobago",
    areaCode: "+1",
    currencyCode: "TTD",
  },
  {
    id: "TN",
    flag: "TUN",
    country: "Tunisia",
    areaCode: "+216",
    currencyCode: "TND",
  },
  {
    id: "TR",
    flag: "TUR",
    country: "Turkey",
    areaCode: "+90",
    currencyCode: "TRY",
  },
  {
    id: "TM",
    flag: "TKM",
    country: "Turkmenistan",
    areaCode: "+993",
    currencyCode: "TMT",
  },
  {
    id: "TC",
    flag: "TCA",
    country: "Turks and Caicos Islands",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "TV",
    flag: "TUV",
    country: "Tuvalu",
    areaCode: "+688",
    currencyCode: "AUD",
  },
  {
    id: "UG",
    flag: "UGA",
    country: "Uganda",
    areaCode: "+256",
    currencyCode: "UGX",
  },
  {
    id: "UA",
    flag: "UKR",
    country: "Ukraine",
    areaCode: "+380",
    currencyCode: "UAH",
  },
  {
    id: "AE",
    flag: "ARE",
    country: "United Arab Emirates",
    areaCode: "+971",
    currencyCode: "AED",
  },
  {
    id: "GB",
    flag: "GBR",
    country: "United Kingdom",
    areaCode: "+44",
    currencyCode: "GBP",
  },
  {
    id: "US",
    flag: "USA",
    country: "United States",
    areaCode: "+1",
    currencyCode: "USD",
  },
  {
    id: "UY",
    flag: "URY",
    country: "Uruguay",
    areaCode: "+598",
    currencyCode: "UYU",
  },
  {
    id: "UZ",
    flag: "UZB",
    country: "Uzbekistan",
    areaCode: "+998",
    currencyCode: "UZS",
  },
  {
    id: "VU",
    flag: "VUT",
    country: "Vanuatu",
    areaCode: "+678",
    currencyCode: "VUV",
  },
  {
    id: "VA",
    flag: "VAT",
    country: "Vatican City",
    areaCode: "+39",
    currencyCode: "EUR",
  },
  {
    id: "VE",
    flag: "VEN",
    country: "Venezuela",
    areaCode: "+58",
    currencyCode: "VES",
  },
  {
    id: "VN",
    flag: "VNM",
    country: "Vietnam",
    areaCode: "+84",
    currencyCode: "VND",
  },
  {
    id: "WF",
    flag: "WLF",
    country: "Wallis and Futuna",
    areaCode: "+681",
    currencyCode: "XPF",
  },
  {
    id: "EH",
    flag: "ESH",
    country: "Western Sahara",
    areaCode: "+212",
    currencyCode: "MAD",
  },
  {
    id: "YE",
    flag: "YEM",
    country: "Yemen",
    areaCode: "+967",
    currencyCode: "YER",
  },
  {
    id: "ZM",
    flag: "ZMB",
    country: "Zambia",
    areaCode: "+260",
    currencyCode: "ZMW",
  },
  {
    id: "ZW",
    flag: "ZWE",
    country: "Zimbabwe",
    areaCode: "+263",
    currencyCode: "ZWL",
  },
];
